ALTER TABLE leaderboard
  ADD COLUMN wins TINYINT UNSIGNED NULL AFTER score,
  ADD COLUMN draws TINYINT UNSIGNED NULL AFTER wins,
  ADD COLUMN losses TINYINT UNSIGNED NULL AFTER draws,
  ADD COLUMN points SMALLINT UNSIGNED NULL AFTER losses;

UPDATE leaderboard
SET
  wins = CASE WHEN score >= 100 THEN 38 ELSE NULL END,
  draws = CASE WHEN score >= 100 THEN 0 ELSE NULL END,
  losses = CASE WHEN score >= 100 THEN 0 ELSE NULL END,
  points = CASE WHEN score >= 100 THEN 114 ELSE NULL END
WHERE wins IS NULL OR draws IS NULL OR losses IS NULL OR points IS NULL;
